# Generated by Django 3.1.6 on 2021-02-01 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('logo_png', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
