# Generated by Django 3.1.6 on 2021-02-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo_png',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
