# Generated by Django 3.1.6 on 2021-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Preparing', 'Preparing'), ('Waiting Review', 'Waiting Review'), ('Ready', 'Ready'), ('Canceled', 'Canceled')], default='New', max_length=50),
        ),
    ]
