# Generated by Django 3.1.6 on 2021-02-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
