# Generated by Django 3.1.6 on 2021-02-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210202_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
