# Generated by Django 3.1.6 on 2021-02-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_progress_prgress_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='prgress_note',
            new_name='progress_note',
        ),
    ]
