# Generated by Django 3.1.6 on 2021-02-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_progress_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ('created_at',)},
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
