# Generated by Django 3.1.6 on 2021-02-02 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_auto_20210202_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='date_time',
        ),
        migrations.AddField(
            model_name='progress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
